### PR TITLE
feat: relaxed dependencies

### PR DESCRIPTION
**Pull request by 8ball030**
Hi there.

We were having problems integrating this into our ledger.

https://github.com/valory-xyz/open-aea/tree/main/plugins

To be used in conjunction with;

https://github.com/valory-xyz/open-autonomy

If at all possible, would you consider relaxing this requirement?

I believe that all tests will be unaffected.

### CODE REVIEW

**Comment by michaelhly** [comment]
@8ball030 please bump poetry, CI failing due to:
```sh
Creating virtualenv solana in /home/runner/work/solana-py/solana-py/.venv

  RuntimeError

  The lock file is not compatible with the current version of Poetry.
  Upgrade Poetry to be able to read the lock file or, alternatively, regenerate the lock file with the `poetry lock` command.

  at ~/.local/venv/lib/python3.9/site-packages/poetry/packages/locker.py:4[8](https://github.com/michaelhly/solana-py/actions/runs/4505888599/jobs/7932430013?pr=347#step:6:9)2 in _get_lock_data
      478│                 "Upgrade Poetry to ensure the lock file is read properly or, alternatively, "
      47[9](https://github.com/michaelhly/solana-py/actions/runs/4505888599/jobs/7932430013?pr=347#step:6:10)│                 "regenerate the lock file with the `poetry lock` command."
      480│             )
      481│         elif not lock_version_allowed:
    → 482│             raise RuntimeError(
      483│                 "The lock file is not compatible with the current version of Poetry.\n"
      484│                 "Upgrade Poetry to be able to read the lock file or, alternatively, "
      485│                 "regenerate the lock file with the `poetry lock` command."
      486│             )
```

**Comment by 8ball030** [comment]
image

please lmk if this is not as expected.

**Comment by kevinheavey** [comment]
@michaelhly i do not.

@8ball030 please specify a version range so people can use both 9.x and 10.x. Right now this PR stops people using 10.x

**Comment by 8ball030** [comment]
@kevinheavey 
I this the last commit should fix this;

image

```
websockets = ">=9.0,<11.0"
```

**Comment by 8ball030** [comment]
@michaelhly @kevinheavey 

Thanks again for the reviews and feedback.

i would love to make a pr into https://github.com/kevinheavey/anchorpy

Which references the websockets change and this new solana version.

Is that ok?

**Comment by kevinheavey** [comment]
@8ball030 yes please!

**Comment by 8ball030** [comment]
@kevinheavey 

Actioned here;
https://github.com/kevinheavey/anchorpy/pull/119

**Pull request merged**
