### PR TITLE
Default to client's commitment in confirm_transaction, send_transaction and Token

### PR DESCRIPTION
**Pull request by kevinheavey**
Currently if commitment is not specified in `confirm_transaction`, `send_transaction`, `send_raw_transasction`, and the methods on `Token` and `AsyncToken`, then it defaults to `types.TxOpts()` (which entails Finalized commitment).

This changes the default to `types.TxOpts(preflight_commitment=self._commitment)` (or `self._conn.commitment` for `Token` and `AsyncToken`) which is probably what a lot of people thought it was doing anyway, and consistent with how we use commitment elsewhere.

Also exposes `Client.commitment` as a property like in web3.js.

Also moves the `get_recent_performance_samples` integration tests so they can run concurrently and not slow down the CI. This is needed because the tests run faster now, and `get_recent_performance_samples` requires the validator to be up and running for at least a minute.

### CODE REVIEW

**Comment by kevinheavey** [comment]
@michaelhly this first test is failing because the client now isn't getting charged a fee for the transaction, any idea why?

```@pytest.mark.integration
    def test_send_transaction_and_get_balance(stubbed_sender, stubbed_receiver, test_http_client):
        """Test sending a transaction to localnet."""
        # Create transfer tx to transfer lamports from stubbed sender to stubbed_receiver
        transfer_tx = Transaction().add(
            sp.transfer(sp.TransferParams(from_pubkey=stubbed_sender.public_key, to_pubkey=stubbed_receiver, lamports=1000))
        )
        resp = test_http_client.send_transaction(transfer_tx, stubbed_sender)
        assert_valid_response(resp)
        # Confirm transaction
        test_http_client.confirm_transaction(resp["result"])
        # Check balances
        resp = test_http_client.get_balance(stubbed_sender.public_key)
        assert_valid_response(resp)
>       assert resp["result"]["value"] == 9999994000
E       assert 9999999000 == 9999994000```

**Comment by michaelhly** [comment]
Possibly related to https://github.com/michaelhly/solana-py/pull/217#issue-1194720464?

**Comment by kevinheavey** [comment]
Ugh the token client tests are flaky now

**Review by michaelhly — APPROVED** [review]
Let's just comment out the flaky test and add a TODO to fix it later?

**Comment by kevinheavey** [comment]
The `test_token` fixture is flaky so we'd have to comment out the whole file 😅

**Comment by crypt0miester** [comment]
should I wait for this to be merged until then do the memo program PR?

**Comment by kevinheavey** [comment]
> should I wait for this to be merged, then do the memo program PR? 

Don't wait, this could take a while

**Comment by crypt0miester** [comment]
> > should I wait for this to be merged, then do the memo program PR? 
> 
> Don't wait, this could take a while

sure mate. cheers.

**Pull request merged**
