### PR TITLE
Delete PublicKey, AccountMeta and TransactionInstruction

### PR DESCRIPTION
**Pull request by kevinheavey**
Initially this was just going to remove PublicKey in favour of the Solders `Pubkey`, but once you do this the solana-py `AccountMeta` and `TransactionInstruction` become completely redundant too

### CODE REVIEW

**Comment by kevinheavey** [comment]
@michaelhly since this is a long one I'll warn you that the diffs are all equally boring

**Review by michaelhly — APPROVED** [review]
Tests passes ... so LGTM!

**Comment by michaelhly** [comment]
@kevinheavey why don't we add to the README that you need to also install solders as a dependency?

**Comment by kevinheavey** [comment]
@michaelhly yeah we should do that before next release. I'm still figuring out what I want do with Transaction/VersionedTransaction

**Pull request merged**
